#! /bin/sh

sxhkd &

bspc config external_rules_command "$(which external_rules)"

bspc config border_width            2
bspc config window_gap             10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config normal_border_color "#AAAAAA"
bspc config active_border_color "#FFFFFF"
bspc config focused_border_color "#00A0FF"
bspc config presel_border_color "#3BFF7B"
bspc config urgent_border_color "#FF5500"
bspc config focused_locked_border_color "#99DAFF"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc monitor DVI-I-1 -n L
bspc monitor DP-3 -n R
bspc monitor R -s L
bspc monitor L -d I II III IV V
bspc monitor R -d VI VII VIII IX X

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

panel &
