#! /bin/sh

sxhkd &
panel &

bspc config external_rules_command "$(which external_rules)"

bspc config border_width                1
bspc config window_gap                  0

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config history_aware_focus         true
bspc config focus_follows_pointer       true
bspc config normal_border_color         "#252525" # 212121
bspc config active_border_color         "#AAAAAA" # FFFFFF
bspc config focused_border_color        "#0070FF" # 0277BD
bspc config presel_border_color         "#008715" # 3BFF7B
bspc config urgent_border_color         "#D75B00" # FF5500
bspc config focused_locked_border_color "#00FFFF"
bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.1

bspc config pointer_modifier    mod4

#bspc monitor LVDS-0 -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'
if [ "$HOSTNAME" == "desktopArch" ]; then
    bspc monitor -d I II III IV V VI VII VIII IX X
    bspc monitor DVI-I-1 -n L
    bspc monitor DP-5 -n R
    bspc monitor L -s R
    bspc monitor R -d '1' '2' '3' '4' '5' '6' '7'
    bspc monitor L -d '8' '9' '10'
elif [ "$HOSTNAME" == "laptopArch" ]; then
    bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'
fi

#desktop_config() {
#    bspc config $1 $2
#    for M in $(bspc query -M); do
#        bspc config -m $M $1 $2
#    done
#}

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a i3lock manage=off


# REALLY NOT SURE ABOUT THIS ONE. the goal is to make the 'hangouts' window floating by default
#bspc rule -a Firefox:Navigator state=floating
